import type { AppSettings, ReviewHistory, StudyCard, SyncQueueItem } from '../types.js';
import { deleteQueueItem,getCard,getQueue,getSettings,saveCard,saveConflict,saveHistory,saveQueueItem,saveSettings } from '../storage/db.js';
import { canonicalRequest,encodePayload,signRequest } from './crypto.js';
import { nowIso,uid } from '../utils/core.js';
interface PullResult{ok:boolean;serverTime:string;cards:StudyCard[];history:ReviewHistory[];syncResults:Array<{requestId:string;action:string;outcome:string;cardId:string;message:string}>;error?:string}
export interface SyncReport{pushed:number;pulledCards:number;pulledHistory:number;conflicts:number;pending:number}
export function isAllowedGasUrl(url:string):boolean{try{const p=new URL(url);return p.protocol==='https:'&&p.hostname==='script.google.com'&&/^\/macros\/s\/[A-Za-z0-9_-]+\/exec$/u.test(p.pathname)}catch{return false}}
async function envelope(settings:AppSettings,item:SyncQueueItem){const timestamp=nowIso(),nonce=uid('nonce');const canonical=canonicalRequest(item.action,timestamp,nonce,item.requestId,item.payload);return{action:item.action,timestamp,nonce,requestId:item.requestId,payload:item.payload,signature:await signRequest(settings.syncSecret,canonical)}}
async function post(settings:AppSettings,item:SyncQueueItem){const response=await fetch(settings.gasUrl,{method:'POST',mode:'no-cors',cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',body:JSON.stringify(await envelope(settings,item))});if(response.type!=='opaque'&&!response.ok)throw new Error(`Sync POST failed: ${response.status}`)}
function sandboxJsonp<T>(url:URL):Promise<T>{return new Promise((resolve,reject)=>{const callback=`__work1_${uid('cb').replaceAll('-','_')}`;const token=uid('sandbox');const iframe=document.createElement('iframe');iframe.hidden=true;iframe.sandbox.add('allow-scripts');iframe.src='./sync-sandbox.html';iframe.title='同期応答サンドボックス';url.searchParams.set('callback',callback);let done=false;const cleanup=()=>{window.removeEventListener('message',onMessage);clearTimeout(timer);iframe.remove()};const finish=(error?:Error,value?:T)=>{if(done)return;done=true;cleanup();error?reject(error):resolve(value as T)};const onMessage=(event:MessageEvent)=>{if(event.source!==iframe.contentWindow)return;const data=event.data as {kind?:unknown;token?:unknown;value?:unknown}|null;if(!data||data.token!==token)return;if(data.kind==='work1-sync-error'){finish(new Error('Apps Script応答を読み込めませんでした。'));return}if(data.kind==='work1-sync-response')finish(undefined,data.value as T)};const timer=window.setTimeout(()=>finish(new Error('同期の読み込みがタイムアウトしました。')),15000);window.addEventListener('message',onMessage);iframe.addEventListener('load',()=>iframe.contentWindow?.postMessage({kind:'work1-sync-request',token,callback,url:url.toString()},'*'),{once:true});document.body.append(iframe)})}
function validPullResult(value:unknown):value is PullResult{if(!value||typeof value!=='object')return false;const item=value as Partial<PullResult>;return typeof item.ok==='boolean'&&typeof item.serverTime==='string'&&Array.isArray(item.cards)&&Array.isArray(item.history)&&Array.isArray(item.syncResults)}
async function pull(settings:AppSettings):Promise<PullResult>{const action='pull',requestId=uid('pull'),timestamp=nowIso(),nonce=uid('nonce'),payload={since:settings.lastSyncAt};const url=new URL(settings.gasUrl);url.searchParams.set('action',action);url.searchParams.set('timestamp',timestamp);url.searchParams.set('nonce',nonce);url.searchParams.set('requestId',requestId);url.searchParams.set('payload',encodePayload(payload));url.searchParams.set('signature',await signRequest(settings.syncSecret,canonicalRequest(action,timestamp,nonce,requestId,payload)));const value=await sandboxJsonp<unknown>(url);if(!validPullResult(value))throw new Error('Apps Scriptから不正な同期応答を受信しました。');if(!value.ok)throw new Error(value.error||'Apps Script pull failed');return value}
const LOCAL_META: Array<keyof StudyCard>=['cardNumber','profileId','deckId','noteId','noteTypeId','templateId','queue','position','flag','suspended','buriedUntil','marked','typedAnswer','siblingGroup','originalDeckId','filteredDeckId','customData','imageOcclusion'];
function mergeRemote(remote:StudyCard,local?:StudyCard):StudyCard{if(!local)return remote;const result={...remote} as StudyCard;for(const key of LOCAL_META){if((remote as unknown as Record<string,unknown>)[key]===undefined)(result as unknown as Record<string,unknown>)[key]=(local as unknown as Record<string,unknown>)[key]}return result}
async function preserveConflict(item:SyncQueueItem,message:string){const card=item.payload.card as StudyCard|undefined;if(!card)return;await saveConflict({id:uid('conflict'),requestId:item.requestId,cardId:card.id,createdAt:nowIso(),message});const t=nowIso(),requestId=uid('req');const copy={...card,id:uid('card'),question:`${card.question}（競合コピー）`,tags:[...new Set([...card.tags,'sync-conflict'])],createdAt:t,updatedAt:t,deletedAt:null,version:card.version+1,lastRequestId:requestId};await saveCard(copy)}
async function applyPull(result:PullResult,queue:SyncQueueItem[]):Promise<number>{const byId=new Map(queue.map(i=>[i.requestId,i]));let conflicts=0;for(const s of result.syncResults){const q=byId.get(s.requestId);if(!q)continue;if(s.outcome==='conflict'){await preserveConflict(q,s.message||'Remote card was newer.');conflicts++}await deleteQueueItem(s.requestId)}for(const remote of result.cards){const local=await getCard(remote.id,true);if(!local||remote.updatedAt>=local.updatedAt||remote.deletedAt)await saveCard(mergeRemote(remote,local),false)}for(const h of result.history)await saveHistory(h,false);return conflicts}
export async function syncNow(onStatus?:(m:string)=>void):Promise<SyncReport>{if(!navigator.onLine)throw new Error('オフラインです。記録は端末内に保存されています。');const settings=await getSettings();if(!isAllowedGasUrl(settings.gasUrl)||settings.syncSecret.length<16)throw new Error('設定画面でApps Script URLと同期シークレットを設定してください。');const queue=(await getQueue()).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));let pushed=0;for(const item of queue){onStatus?.(`未同期データを送信中 ${pushed+1}/${queue.length}`);const next={...item,attempts:item.attempts+1};await saveQueueItem(next);await post(settings,next);pushed++}onStatus?.('Google Sheetsから更新を確認中');const result=await pull(settings);const conflicts=await applyPull(result,await getQueue());await saveSettings({...settings,lastSyncAt:result.serverTime});return{pushed,pulledCards:result.cards.length,pulledHistory:result.history.length,conflicts,pending:(await getQueue()).length}}
