import assert from 'node:assert/strict';
import http from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import path from 'node:path';
import { chromium, webkit } from 'playwright';
const dist=path.resolve('dist');
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.svg':'image/svg+xml'};
const server=http.createServer(async(req,res)=>{try{const pathname=new URL(req.url??'/', 'http://localhost').pathname;let file=path.join(dist,pathname==='/'?'index.html':pathname.replace(/^\//,''));const info=await stat(file);if(info.isDirectory())file=path.join(file,'index.html');const data=await readFile(file);res.writeHead(200,{'Content-Type':mime[path.extname(file)]??'application/octet-stream','Cache-Control':'no-store'});res.end(data)}catch{res.writeHead(404);res.end('not found')}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();if(!address||typeof address==='string')throw new Error('server');const url=`http://127.0.0.1:${address.port}/`;
for(const [name,engine] of [['chromium',chromium],['webkit',webkit]]){
 const browser=await engine.launch({headless:true});const context=await browser.newContext({viewport:{width:1024,height:768}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.goto(url,{waitUntil:'networkidle'});await page.waitForSelector('#page-title');assert.equal(await page.locator('#page-title').textContent(),'暗記カード',`${name}: boot`);assert.equal(errors.length,0,`${name}: no page error after boot`);
 await page.locator('#add-card-button').click();await page.locator('#card-number').fill('E2E-001');await page.locator('#card-question').fill('2+2');await page.locator('#card-answer').fill('4');await page.locator('#card-form').evaluate(form=>form.requestSubmit());await page.waitForTimeout(150);assert.equal(await page.locator('#card-dialog').getAttribute('open'),null,`${name}: dialog closes`);
 await page.locator('[data-route="cards"]').click();await page.waitForTimeout(100);assert.ok((await page.locator('#view').innerText()).includes('E2E-001'),`${name}: card visible`);
 await page.locator('[data-route="anki"]').click();await page.waitForTimeout(150);const ankiText=await page.locator('#view').innerText();for(const heading of ['Anki互換センター','デッキ / サブデッキ','ノートを追加','ブラウザ / 高度な検索','フィルターデッキ / Custom Study','ノートタイプ / フィールド / カードテンプレート','FSRS-6 / デッキオプション','プロファイル','インポート / エクスポート / 自動バックアップ'])assert.ok(ankiText.includes(heading),`${name}: ${heading}`);
 const addSection=page.locator('.anki-panel').filter({has:page.getByRole('heading',{name:'ノートを追加'})});await addSection.locator('textarea[data-field="Front"]').fill('Capital of Japan?');await addSection.locator('textarea[data-field="Back"]').fill('Tokyo');await addSection.getByRole('button',{name:'ノートを保存してカード生成'}).click();await page.waitForTimeout(250);
 const counts=await page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('work_1_study_cards');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});const count=store=>new Promise((resolve,reject)=>{const tx=db.transaction(store);const r=tx.objectStore(store).count();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return{cards:await count('cards'),history:await count('history')}});assert.ok(counts.cards>=2,`${name}: note generated card`);
 await page.locator('[data-route="home"]').click();await page.waitForTimeout(100);const primary=page.getByRole('button',{name:/学習モードを選ぶ|今日の復習を始める/});await primary.click();await page.locator('#study-mode').selectOption('new');await page.locator('#study-form').evaluate(form=>form.requestSubmit());await page.waitForSelector('#review-screen:not([hidden])');await page.locator('#show-answer').click();await page.locator('[data-rating="good"]').click();await page.waitForTimeout(250);
 const history=await page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('work_1_study_cards');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return await new Promise((resolve,reject)=>{const tx=db.transaction('history');const r=tx.objectStore('history').count();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})});assert.ok(history>=1,`${name}: review history persisted`);
 await page.reload({waitUntil:'networkidle'});await page.locator('[data-route="cards"]').click();assert.ok((await page.locator('#view').innerText()).includes('E2E-001'),`${name}: same-device persistence after reload`);assert.equal(errors.length,0,`${name}: no uncaught runtime errors`);await browser.close();
}
server.close();process.stdout.write('browser-e2e: chromium + webkit ok\n');
