import type { Rating, ReviewHistory, StudyCard } from '../types.js';
const DAY=86400000;
export function cardStateCounts(cards:StudyCard[]){const result={new:0,learning:0,review:0,relearning:0,suspended:0,buried:0};for(const c of cards){if(c.suspended){result.suspended++;continue}if(c.buriedUntil&&new Date(c.buriedUntil).getTime()>Date.now())result.buried++;const q=c.queue??(c.schedule.reps?'review':'new');result[q]++}return result}
export function ratingCounts(history:ReviewHistory[]){const out:Record<Rating,number>={again:0,hard:0,good:0,easy:0};for(const h of history)out[h.rating]++;return out}
export function trueRetention(history:ReviewHistory[]){const reviews=history.filter(h=>['again','hard','good','easy'].includes(h.rating));const remembered=reviews.filter(h=>h.isCorrect).length;return{reviews:reviews.length,remembered,rate:reviews.length?remembered/reviews.length:0}}
export function forecast(cards:StudyCard[],days=30,now=new Date()){const start=new Date(now);start.setHours(0,0,0,0);const out=Array.from({length:days},(_,i)=>({day:new Date(start.getTime()+i*DAY).toISOString().slice(0,10),count:0}));for(const c of cards){if(c.deletedAt||c.suspended||c.schedule.reps===0)continue;const due=Math.floor((new Date(c.schedule.due).getTime()-start.getTime())/DAY);if(due<0){const first=out[0];if(first)first.count++}else if(due<days){const item=out[due];if(item)item.count++}}return out}
export function intervalHistogram(cards:StudyCard[]){const bins=[{label:'<1d',min:0,max:1,count:0},{label:'1-7d',min:1,max:7,count:0},{label:'1-4w',min:7,max:30,count:0},{label:'1-6mo',min:30,max:180,count:0},{label:'6-12mo',min:180,max:365,count:0},{label:'>1y',min:365,max:Infinity,count:0}];for(const c of cards){if(!c.schedule.lastReview)continue;const interval=Math.max(0,(new Date(c.schedule.due).getTime()-new Date(c.schedule.lastReview).getTime())/DAY);const bin=bins.find(b=>interval>=b.min&&interval<b.max);if(bin)bin.count++}return bins}
export function hourlyBreakdown(history:ReviewHistory[]){const hours=Array.from({length:24},(_,hour)=>({hour,count:0,correct:0}));for(const h of history){const hour=new Date(h.reviewedAt).getHours();const item=hours[hour];if(item){item.count++;if(h.isCorrect)item.correct++}}return hours}
export function streak(history:ReviewHistory[],now=new Date()){const days=new Set(history.map(h=>h.reviewedAt.slice(0,10)));let count=0;const d=new Date(now);d.setHours(0,0,0,0);while(days.has(d.toISOString().slice(0,10))){count++;d.setDate(d.getDate()-1)}return count}
