const ALLOWED=new Set(['A','B','STRONG','I','EM','U','S','BR','P','DIV','SPAN','HR','UL','OL','LI','TABLE','THEAD','TBODY','TR','TH','TD','RUBY','RT','RP','DETAILS','SUMMARY','CODE','PRE','BLOCKQUOTE','IMG','AUDIO','VIDEO','SOURCE','SUB','SUP','MARK']);
const ALLOWED_ATTR=new Set(['href','src','alt','title','controls','loop','autoplay','playsinline','class','dir','lang','data-lang','id']);
function safeUrl(value:string,kind:'href'|'src'):boolean{try{if(value.startsWith('#'))return kind==='href';if(value.startsWith('data:'))return kind==='src'&&/^data:(image|audio|video)\//i.test(value);const url=new URL(value,document.baseURI);return['https:','http:','mailto:'].includes(url.protocol)&&(kind==='href'||url.protocol!=='mailto:')}catch{return false}}
function sanitizeNode(node:Node):void{for(const child of [...node.childNodes]){if(child.nodeType===Node.ELEMENT_NODE){const element=child as HTMLElement;if(!ALLOWED.has(element.tagName)){const fragment=document.createDocumentFragment();while(element.firstChild)fragment.append(element.firstChild);element.replaceWith(fragment);sanitizeNode(node);continue}for(const attr of [...element.attributes]){const name=attr.name.toLowerCase();if(name.startsWith('on')||!ALLOWED_ATTR.has(name))element.removeAttribute(attr.name)}const href=element.getAttribute('href');if(href&&!safeUrl(href,'href'))element.removeAttribute('href');const src=element.getAttribute('src');if(src&&!safeUrl(src,'src'))element.removeAttribute('src');if(element.tagName==='A'){element.setAttribute('rel','noopener noreferrer');element.setAttribute('target','_blank')}sanitizeNode(element)}else if(child.nodeType!==Node.TEXT_NODE)child.remove()}}
function sanitizedBody(value:string):HTMLElement{const doc=new DOMParser().parseFromString(value,'text/html');sanitizeNode(doc.body);return doc.body}
function looksLikeHtml(value:string):boolean{return/<\/?[a-z][^>]*>/i.test(value)}
export async function renderRich(element:HTMLElement,value:string):Promise<void>{if(looksLikeHtml(value)){const body=sanitizedBody(value);element.replaceChildren(...[...body.childNodes].map(node=>document.importNode(node,true)))}else element.textContent=value;const mathJax=(window as typeof window&{MathJax?:{typesetPromise?:(nodes?:HTMLElement[])=>Promise<unknown>}}).MathJax;try{await mathJax?.typesetPromise?.([element])}catch{}}
export function plainText(value:string):string{return sanitizedBody(value).textContent?.replace(/\s+/g,' ').trim()??''}
export function replayMedia(root:HTMLElement):void{root.querySelectorAll<HTMLMediaElement>('audio,video').forEach(media=>{try{media.currentTime=0;void media.play()}catch{}});const tts=root.querySelectorAll<HTMLElement>('.anki-tts');if('speechSynthesis'in window)for(const node of tts){const utterance=new SpeechSynthesisUtterance(node.textContent??'');const lang=node.dataset.lang;if(lang)utterance.lang=lang.replace('_','-');speechSynthesis.speak(utterance)}}
