import type { AppSettings, ReviewMode, ReviewSession, ReviewStyle, StudyCard } from '../types.js';
import { createCard,persistCard,validateCardDraft,type CardDraft } from '../cards/cards.js';
import { selectCards } from '../review/select.js';
import { ReviewController } from '../review/controller.js';
import { exportCsv,exportJson,importJson } from '../storage/backup.js';
import { clearCurrentSession,getAnkiState,getCards,getCurrentSession,getHistory,getQueue,getSettings,saveCard,saveQueueItem,saveSettings } from '../storage/db.js';
import { summarize,dailyCounts,tagAccuracy } from '../statistics/stats.js';
import { cardStateCounts,forecast,intervalHistogram,ratingCounts,streak,trueRetention } from '../statistics/anki-stats.js';
import { isAllowedGasUrl,syncNow } from '../sync/client.js';
import { button,clear,el } from '../ui/dom.js';
import { formatDuration,normalizeTags,nowIso,uid } from '../utils/core.js';
import { isDue } from '../scheduler/scheduler.js';
import { AnkiCenter } from '../anki/center.js';
import { initializeAnkiCollection,presetForCard } from '../anki/collection.js';
import { DEFAULT_DECK_ID } from '../anki/defaults.js';
import { plainText } from '../ui/rich.js';
function byId<T extends HTMLElement>(id:string):T{const n=document.getElementById(id);if(!n)throw new Error(`Missing #${id}`);return n as T}
type Route='home'|'cards'|'anki'|'stats'|'settings';
export class App{
 private route:Route='home';private readonly view=byId<HTMLElement>('view');private readonly title=byId<HTMLElement>('page-title');private readonly status=byId<HTMLElement>('status-message');private readonly syncButton=byId<HTMLButtonElement>('sync-button');private readonly syncBadge=byId<HTMLElement>('sync-badge');private readonly addButton=byId<HTMLButtonElement>('add-card-button');private readonly cardDialog=byId<HTMLDialogElement>('card-dialog');private readonly cardForm=byId<HTMLFormElement>('card-form');private readonly studyDialog=byId<HTMLDialogElement>('study-dialog');private readonly studyForm=byId<HTMLFormElement>('study-form');private readonly review:ReviewController;private readonly anki:AnkiCenter;private statusTimer=0;
 constructor(){this.review=new ReviewController(async()=>{await this.refresh();void this.autoSync()});this.anki=new AnkiCenter({showStatus:(m,e)=>this.showStatus(m,e),startCards:async(cards,mode,deckId,filteredDeckId)=>this.startCards(cards,mode,deckId,filteredDeckId),refresh:()=>this.refresh()});this.bindGlobalEvents()}
 async init(){const migrated=await initializeAnkiCollection();await this.updateSyncBadge();await this.render();const session=await getCurrentSession();if(session&&session.cursor<session.queue.length)this.showStatus(`途中の学習があります（${session.cursor}/${session.queue.length}）。「続きから再開」を選べます。`,false,8000);if(migrated.migratedCards||migrated.notesAdded)this.showStatus(`既存データをAnki形式へ移行しました：カード${migrated.migratedCards}件・ノート${migrated.notesAdded}件。`);if(navigator.onLine)void this.autoSync()}
 private bindGlobalEvents(){document.querySelectorAll<HTMLButtonElement>('[data-route]').forEach(item=>item.addEventListener('click',()=>{const r=item.dataset.route as Route|undefined;if(r)void this.navigate(r)}));this.addButton.addEventListener('click',()=>void this.openCardDialog());this.syncButton.addEventListener('click',()=>void this.performSync());this.cardForm.addEventListener('submit',e=>void this.handleCardSubmit(e));this.studyForm.addEventListener('submit',e=>void this.handleStudySubmit(e));window.addEventListener('online',()=>{this.showStatus('オンラインに戻りました。未同期データを送信します。');void this.autoSync()});window.addEventListener('offline',()=>this.showStatus('オフラインです。カードと学習履歴は端末内に保存されます。'));}
 private async navigate(route:Route){this.route=route;document.querySelectorAll<HTMLButtonElement>('[data-route]').forEach(i=>i.classList.toggle('is-active',i.dataset.route===route));await this.render();this.view.focus({preventScroll:true})}
 private async render(){clear(this.view);if(this.route==='home')await this.renderHome();else if(this.route==='cards')await this.renderCards();else if(this.route==='anki'){this.title.textContent='Anki機能';await this.anki.render(this.view)}else if(this.route==='stats')await this.renderStats();else await this.renderSettings();await this.updateSyncBadge()}
 private async renderHome(){this.title.textContent='暗記カード';const[cards,history,state]=await Promise.all([getCards(),getHistory(),getAnkiState()]);const now=new Date();const usable=cards.filter(c=>!c.suspended&&(!c.buriedUntil||new Date(c.buriedUntil).getTime()<=now.getTime()));const due=usable.filter(c=>c.schedule.reps>0&&isDue(c.schedule,now)).length;const fresh=usable.filter(c=>c.schedule.reps===0).length;const today=summarize(history,1,now);const hero=el('section',{className:'hero'});const lead=el('div',{className:'hero-card'});lead.append(el('p',{className:'eyebrow',text:'TODAY'}),el('h2',{className:'hero-title',text:due?`復習が ${due} 枚あります`:'今日の復習は完了です'}),el('p',{className:'muted',text:'FSRS-6、デッキ、Cloze、Image OcclusionなどAnki型の学習機能を利用できます。'}));const actions=el('div',{className:'hero-actions'});const start=button(due?'今日の復習を始める':'学習モードを選ぶ','primary-button');start.addEventListener('click',()=>void this.openStudyDialog(due?'due':undefined));actions.append(start);const resume=await getCurrentSession();if(resume){const b=button('続きから再開');b.addEventListener('click',()=>void this.review.resume(resume));actions.append(b)}const manage=button('Anki機能を管理');manage.addEventListener('click',()=>void this.navigate('anki'));actions.append(manage);lead.append(actions);hero.append(lead);const metrics=el('div',{className:'metric-grid'});const metric=(v:string,l:string)=>{const n=el('div',{className:'metric'});n.append(el('strong',{text:v}),el('span',{text:l}));return n};metrics.append(metric(String(due),'今日の復習'),metric(String(fresh),'新しいカード'),metric(String(today.studied),'今日の学習'),metric(`${Math.round(today.accuracy*100)}%`,'今日の正答率'));hero.append(metrics);const deckSection=el('section',{className:'section'});deckSection.append(el('h2',{text:'デッキ'}));const grid=el('div',{className:'mode-grid'});for(const deck of state.decks.filter(d=>d.profileId===state.activeProfileId)){const deckCards=cards.filter(c=>c.deckId===deck.id||state.decks.find(x=>x.id===c.deckId)?.name.startsWith(`${deck.name}::`));const b=el('button',{className:'mode-card',attrs:{type:'button'}});b.append(el('strong',{text:deck.name}),el('span',{text:`${deckCards.length}枚` }));b.addEventListener('click',()=>void this.startDeck(deck.id));grid.append(b)}deckSection.append(grid);hero.append(deckSection);this.view.append(hero)}
 private async startDeck(deckId:string){const[cards,history,state]=await Promise.all([getCards(),getHistory(),getAnkiState()]);const deck=state.decks.find(d=>d.id===deckId);const preset=state.presets.find(p=>p.id===deck?.presetId)??state.presets[0];const selected=selectCards(cards,history,{mode:'deck',state,deckId,newLimit:preset?.dailyNewLimit??20,reviewLimit:preset?.dailyReviewLimit??200});if(!selected.length){const fresh=selectCards(cards,history,{mode:'new',state,deckId,newLimit:preset?.dailyNewLimit??20});if(!fresh.length){this.showStatus('このデッキに学習対象カードがありません。',true);return}await this.startCards(fresh,'new',deckId);return}await this.startCards(selected,'deck',deckId)}
 private async renderCards(){this.title.textContent='カード';const cards=(await getCards()).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));const wrap=el('section');const row=el('div',{className:'search-row'});const search=el('input',{attrs:{type:'search',placeholder:'番号・問題・答え・タグを検索'}});const browser=button('高度なブラウザ');browser.addEventListener('click',()=>void this.navigate('anki'));row.append(search,browser);const list=el('div',{className:'card-list'});wrap.append(row,list);this.view.append(wrap);const draw=(q='')=>{clear(list);const n=q.trim().toLocaleLowerCase();for(const card of cards.filter(c=>!n||[c.cardNumber??'',plainText(c.question),plainText(c.answer),...c.tags].join('\n').toLocaleLowerCase().includes(n)).slice(0,500))list.append(this.cardRow(card));if(!list.children.length)list.append(el('p',{className:'empty',text:'該当するカードがありません。'}))};draw();search.addEventListener('input',()=>draw(search.value))}
 private cardRow(card:StudyCard){const row=el('article',{className:'card-row'});const content=el('div');if(card.cardNumber)content.append(el('p',{className:'card-number',text:`No. ${card.cardNumber}`}));content.append(el('h3',{text:plainText(card.question)}),el('p',{text:`答え：${plainText(card.answer)}`}));for(const tag of card.tags)content.append(el('span',{className:'tag-chip',text:tag}));if(card.suspended)content.append(el('span',{className:'tag-chip',text:'保留'}));if(card.flag)content.append(el('span',{className:'tag-chip',text:`Flag ${card.flag}`}));const actions=el('div',{className:'row-actions'});const edit=button('編集','small-button');edit.addEventListener('click',()=>void this.openCardDialog(card));const dup=button('複製','small-button');dup.addEventListener('click',()=>void this.duplicateCard(card));const remove=button('削除','small-button');remove.addEventListener('click',()=>void this.deleteCard(card));actions.append(edit,dup,remove);row.append(content,actions);return row}
 private async renderStats(){this.title.textContent='学習記録';const[cards,history]=await Promise.all([getCards(),getHistory()]);const today=summarize(history,1),week=summarize(history,7),month=summarize(history,30);const metrics=el('div',{className:'metric-grid'});const m=(v:string,l:string)=>{const n=el('div',{className:'metric'});n.append(el('strong',{text:v}),el('span',{text:l}));return n};metrics.append(m(String(today.studied),'今日'),m(`${Math.round(today.accuracy*100)}%`,'今日の正答率'),m(String(week.studied),'7日間'),m(formatDuration(month.totalMs),'30日学習時間'));this.view.append(metrics);const daily=el('section',{className:'section'});daily.append(el('h2',{text:'直近7日'}));const list=el('div',{className:'bar-list'});const days=dailyCounts(history,7),max=Math.max(1,...days.map(d=>d.count));for(const d of days){const r=el('div',{className:'bar-row'}),track=el('div',{className:'bar-track'}),fill=el('div',{className:'bar-fill'});fill.style.width=`${d.count/max*100}%`;track.append(fill);r.append(el('span',{text:d.day}),track,el('strong',{text:`${d.count}枚`}));list.append(r)}daily.append(list);this.view.append(daily);const tags=el('section',{className:'section'});tags.append(el('h2',{text:'タグ別正答率'}));for(const t of tagAccuracy(cards).slice(0,20))tags.append(el('p',{text:`${t.tag}: ${Math.round(t.accuracy*100)}% (${t.total})`}));this.view.append(tags);const states=cardStateCounts(cards),ratings=ratingCounts(history),ret=trueRetention(history),streakDays=streak(history);const overview=el('section',{className:'section'});overview.append(el('h2',{text:'Anki統計'}));const stateGrid=el('div',{className:'metric-grid'});stateGrid.append(m(String(states.new),'新規'),m(String(states.learning+states.relearning),'学習中'),m(String(states.review),'復習'),m(String(states.suspended),'保留'),m(String(streakDays),'連続日数'),m(`${Math.round(ret.rate*100)}%`,'真の保持率'),m(String(ratings.again),'Again'),m(String(ratings.easy),'Easy'));overview.append(stateGrid);this.view.append(overview);const forecastSection=el('section',{className:'section'});forecastSection.append(el('h2',{text:'30日間の復習予測'}));const forecastList=el('div',{className:'bar-list'});const forecastData=forecast(cards,30),forecastMax=Math.max(1,...forecastData.map(d=>d.count));for(const d of forecastData.slice(0,14)){const r=el('div',{className:'bar-row'}),track=el('div',{className:'bar-track'}),fill=el('div',{className:'bar-fill'});fill.style.width=`${d.count/forecastMax*100}%`;track.append(fill);r.append(el('span',{text:d.day.slice(5)}),track,el('strong',{text:String(d.count)}));forecastList.append(r)}forecastSection.append(forecastList);this.view.append(forecastSection);const intervals=el('section',{className:'section'});intervals.append(el('h2',{text:'復習間隔'}));for(const bin of intervalHistogram(cards))intervals.append(el('p',{text:`${bin.label}: ${bin.count}枚`}));this.view.append(intervals)}
 private async renderSettings(){this.title.textContent='設定';const settings=await getSettings();const grid=el('div',{className:'settings-grid'});const sync=el('section',{className:'settings-card'});sync.append(el('h2',{text:'Google Sheets同期'}));const url=this.input('Apps Script Web App URL',settings.gasUrl,'url');const secret=this.input('同期シークレット','','password');secret.input.placeholder=settings.syncSecret?'保存済み（変更時のみ入力）':'16文字以上';const save=button('同期設定を保存','primary-button');save.addEventListener('click',()=>void this.saveSyncSettings(url.input.value,secret.input.value));sync.append(url.label,secret.label,el('p',{className:'help',text:'カードと学習履歴は端末へ先に保存し、その後Sheetsへ同期します。Anki固有のノートタイプ・デッキ構成はJSONバックアップにも保存されます。'}),save);const backup=el('section',{className:'settings-card'});backup.append(el('h2',{text:'バックアップ / エクスポート'}));const actions=el('div',{className:'button-row'});const json=button('完全JSONを書き出す'),csv=button('CSVを書き出す'),imp=button('JSONを読み込む');const file=el('input',{attrs:{type:'file',accept:'.json,application/json'}});file.hidden=true;json.addEventListener('click',()=>void exportJson());csv.addEventListener('click',()=>void exportCsv());imp.addEventListener('click',()=>file.click());file.addEventListener('change',()=>void this.handleImport(file));actions.append(json,csv,imp,file);backup.append(actions);const prefs=el('section',{className:'settings-card'});prefs.append(el('h2',{text:'学習表示 / 操作'}));const pref=(label:string,checked:boolean)=>{const l=el('label',{className:'check-row',text:label}),i=el('input',{attrs:{type:'checkbox'}});i.checked=checked;l.prepend(i);return{l,i}};const remaining=pref('残りカード数を表示',settings.showRemainingCount!==false),nextTime=pref('回答ボタンに次回間隔を表示',settings.showNextReviewTime!==false),space=pref('Spaceキーで回答',settings.spacebarAnswers!==false),interrupt=pref('回答時に再生中の音声を停止',settings.interruptAudioOnAnswer!==false),autosync=pref('起動/オンライン復帰時に自動同期',settings.autoSync!==false);const savePrefs=button('学習設定を保存','primary-button');savePrefs.addEventListener('click',()=>void(async()=>{const current=await getSettings();await saveSettings({...current,showRemainingCount:remaining.i.checked,showNextReviewTime:nextTime.i.checked,spacebarAnswers:space.i.checked,interruptAudioOnAnswer:interrupt.i.checked,autoSync:autosync.i.checked});this.showStatus('学習設定を保存しました。')}));prefs.append(remaining.l,nextTime.l,space.l,interrupt.l,autosync.l,savePrefs);
    const local=el('section',{className:'settings-card'});local.append(el('h2',{text:'端末データ'}),el('p',{className:'help',text:`未同期データ：${(await getQueue()).length}件。IndexedDBにカード、正誤履歴、ノート、デッキ、設定、バックアップを保存します。`}));const discard=button('途中セッションを破棄','danger-button');discard.addEventListener('click',()=>void clearCurrentSession().then(()=>this.showStatus('セッションを破棄しました。')));local.append(discard);grid.append(sync,prefs,backup,local);this.view.append(grid)}
 private input(text:string,value:string,type='text'){const label=el('label',{text});const input=el('input',{attrs:{type}});input.value=value;label.append(input);return{label,input}}
 private async saveSyncSettings(raw:string,secretRaw:string){const settings=await getSettings(),url=raw.trim();if(url&&!isAllowedGasUrl(url)){this.showStatus('Apps Scriptの /exec URLを入力してください。',true);return}const secret=secretRaw||settings.syncSecret;if(secret&&secret.length<16){this.showStatus('同期シークレットは16文字以上にしてください。',true);return}await saveSettings({...settings,gasUrl:url,syncSecret:secret});this.showStatus('同期設定を保存しました。')}
 private async openCardDialog(card?:StudyCard){byId<HTMLInputElement>('card-id').value=card?.id??'';byId<HTMLInputElement>('card-number').value=card?.cardNumber??'';byId<HTMLTextAreaElement>('card-question').value=plainText(card?.question??'');byId<HTMLTextAreaElement>('card-answer').value=plainText(card?.answer??'');byId<HTMLInputElement>('card-wrong-1').value=card?.distractors[0]??'';byId<HTMLInputElement>('card-wrong-2').value=card?.distractors[1]??'';byId<HTMLInputElement>('card-wrong-3').value=card?.distractors[2]??'';byId<HTMLTextAreaElement>('card-explanation').value=plainText(card?.explanation??'');byId<HTMLInputElement>('card-tags').value=card?.tags.join(', ')??'';byId<HTMLInputElement>('card-favorite').checked=card?.favorite??false;byId<HTMLElement>('card-dialog-title').textContent=card?'カードを編集':'カードを追加';byId<HTMLElement>('card-form-error').textContent='';this.cardDialog.showModal()}
 private cardDraft():CardDraft{return{cardNumber:byId<HTMLInputElement>('card-number').value,question:byId<HTMLTextAreaElement>('card-question').value,answer:byId<HTMLTextAreaElement>('card-answer').value,distractors:[byId<HTMLInputElement>('card-wrong-1').value,byId<HTMLInputElement>('card-wrong-2').value,byId<HTMLInputElement>('card-wrong-3').value],explanation:byId<HTMLTextAreaElement>('card-explanation').value,tagsText:byId<HTMLInputElement>('card-tags').value,favorite:byId<HTMLInputElement>('card-favorite').checked}}
 private async handleCardSubmit(e:SubmitEvent){e.preventDefault();const draft=this.cardDraft(),errors=validateCardDraft(draft);if(errors.length){byId<HTMLElement>('card-form-error').textContent=errors.join(' ');return}const id=byId<HTMLInputElement>('card-id').value;if(!id)await persistCard(createCard(draft));else{const original=(await getCards(true,true)).find(c=>c.id===id);if(!original)return;const requestId=uid('req');const updated={...original,cardNumber:draft.cardNumber?.trim()??'',question:draft.question.trim(),answer:draft.answer.trim(),distractors:draft.distractors.map(v=>v.trim()).filter(Boolean).slice(0,3),explanation:draft.explanation.trim(),tags:normalizeTags(draft.tagsText),favorite:draft.favorite,marked:draft.favorite,updatedAt:nowIso(),version:original.version+1,lastRequestId:requestId};await saveCard(updated);await saveQueueItem({requestId,action:'upsertCard',payload:{card:updated},createdAt:nowIso(),attempts:0})}this.cardDialog.close();this.showStatus('カードを保存しました。');await this.refresh();void this.autoSync()}
 private async duplicateCard(card:StudyCard){await persistCard(createCard({cardNumber:'',question:plainText(card.question)+'（コピー）',answer:plainText(card.answer),distractors:card.distractors,explanation:plainText(card.explanation),tagsText:card.tags.join(','),favorite:card.favorite}));this.showStatus('カードを複製しました。');await this.refresh()}
 private async deleteCard(card:StudyCard){if(!confirm(`「${plainText(card.question).slice(0,80)}」を削除しますか？`))return;const requestId=uid('req'),t=nowIso(),deleted={...card,deletedAt:t,updatedAt:t,version:card.version+1,lastRequestId:requestId};await saveCard(deleted);await saveQueueItem({requestId,action:'deleteCard',payload:{card:deleted},createdAt:t,attempts:0});await this.refresh()}
 private async openStudyDialog(mode?:ReviewMode){const[cards,state]=await Promise.all([getCards(),getAnkiState()]);const tags=[...new Set(cards.flatMap(c=>c.tags))].sort((a,b)=>a.localeCompare(b,'ja'));const tag=byId<HTMLSelectElement>('study-tag');tag.replaceChildren(new Option('すべて',''));for(const t of tags)tag.append(new Option(t,t));const deck=byId<HTMLSelectElement>('study-deck');deck.replaceChildren();for(const d of state.decks.filter(d=>d.profileId===state.activeProfileId))deck.append(new Option(d.name,d.id));if(mode)byId<HTMLSelectElement>('study-mode').value=mode;this.studyDialog.showModal()}
 private async handleStudySubmit(e:SubmitEvent){e.preventDefault();const mode=byId<HTMLSelectElement>('study-mode').value as ReviewMode,style=byId<HTMLSelectElement>('study-style').value as ReviewStyle,tag=byId<HTMLSelectElement>('study-tag').value,deckId=byId<HTMLSelectElement>('study-deck').value||DEFAULT_DECK_ID,examSize=Number(byId<HTMLSelectElement>('study-size').value)||20;const[cards,history,state]=await Promise.all([getCards(),getHistory(),getAnkiState()]);const deck=state.decks.find(d=>d.id===deckId);const preset=state.presets.find(p=>p.id===deck?.presetId)??state.presets[0];const selected=selectCards(cards,history,{mode,tag,examSize,newLimit:preset?.dailyNewLimit??20,reviewLimit:preset?.dailyReviewLimit??200,state,deckId});if(!selected.length){this.studyDialog.close();this.showStatus('この条件で学習するカードがありません。',true);return}this.studyDialog.close();await this.startCards(selected,mode,deckId,undefined,style,tag,examSize)}
 private async startCards(cards:StudyCard[],mode:ReviewMode,deckId?:string,filteredDeckId?:string,style:ReviewStyle='self',tag='',examSize=20){const session:ReviewSession={id:'current',mode,style,queue:cards.map(c=>c.id),cursor:0,answered:0,tag,examSize,startedAt:nowIso(),deckId,filteredDeckId};await this.review.start(session)}
 private async performSync(){this.syncButton.disabled=true;try{const r=await syncNow(m=>this.showStatus(m,false,0));this.showStatus(`同期完了：送信${r.pushed}・カード受信${r.pulledCards}・履歴受信${r.pulledHistory}・未同期${r.pending}`);await this.refresh()}catch(e){this.showStatus(e instanceof Error?e.message:'同期に失敗しました。端末データは保持されています。',true,7000)}finally{this.syncButton.disabled=false}}
 private async autoSync(){const s=await getSettings();if(navigator.onLine&&s.gasUrl&&s.syncSecret&&s.autoSync!==false)await this.performSync()}
 private async updateSyncBadge(){const n=(await getQueue()).length;this.syncBadge.textContent=String(n);this.syncBadge.hidden=n===0}
 private showStatus(message:string,error=false,duration=4500){clearTimeout(this.statusTimer);this.status.textContent=message;this.status.classList.toggle('is-error',error);this.status.hidden=false;if(duration>0)this.statusTimer=window.setTimeout(()=>{this.status.hidden=true},duration)}
 private async refresh(){await this.render();await this.updateSyncBadge()}
 private async handleImport(input:HTMLInputElement){const file=input.files?.[0];if(!file)return;if(!confirm('現在のコレクションをバックアップ内容で置き換えます。続けますか？'))return;try{const r=await importJson(file);this.showStatus(`${r.cards}枚・履歴${r.history}件を復元しました。`);await this.refresh()}catch(e){this.showStatus(e instanceof Error?e.message:'読み込みに失敗しました。',true)}finally{input.value=''}}
}
