interface Point{x:number;y:number;pressure:number} interface Stroke{points:Point[];eraser:boolean}
export class ScratchPad{private readonly ctx:CanvasRenderingContext2D;private strokes:Stroke[]=[];private redoStack:Stroke[]=[];private active:Stroke|null=null;private eraser=false;private observer:ResizeObserver|null=null;private readonly resizeHandler=()=>this.resize();constructor(private readonly canvas:HTMLCanvasElement){const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas 2D is not available');this.ctx=ctx;canvas.style.touchAction='none';canvas.addEventListener('pointerdown',this.down);canvas.addEventListener('pointermove',this.move);canvas.addEventListener('pointerup',this.up);canvas.addEventListener('pointercancel',this.up);if(typeof ResizeObserver!=='undefined'){this.observer=new ResizeObserver(this.resizeHandler);this.observer.observe(canvas);}else{window.addEventListener('resize',this.resizeHandler);window.addEventListener('orientationchange',this.resizeHandler);}this.resize();}
setEraser(v:boolean){this.eraser=v} clear(){this.strokes=[];this.redoStack=[];this.active=null;this.redraw()} undo(){const s=this.strokes.pop();if(s){this.redoStack.push(s);this.redraw()}} redo(){const s=this.redoStack.pop();if(s){this.strokes.push(s);this.redraw()}}
private resize(){const r=this.canvas.getBoundingClientRect();const d=Math.max(1,devicePixelRatio||1);const w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(this.canvas.width===w&&this.canvas.height===h)return;this.canvas.width=w;this.canvas.height=h;this.ctx.setTransform(d,0,0,d,0,0);this.redraw()}
private point(e:PointerEvent):Point{const r=this.canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top,pressure:e.pressure>0?e.pressure:.5}}
private down=(e:PointerEvent)=>{if(e.pointerType==='mouse'&&e.button!==0)return;this.canvas.setPointerCapture(e.pointerId);this.redoStack=[];this.active={points:[this.point(e)],eraser:this.eraser};this.strokes.push(this.active);this.redraw()};
private move=(e:PointerEvent)=>{if(!this.active||!this.canvas.hasPointerCapture(e.pointerId))return;const events=typeof e.getCoalescedEvents==='function'?e.getCoalescedEvents():[e];for(const p of events)this.active.points.push(this.point(p));this.redraw()};
private up=(e:PointerEvent)=>{if(this.canvas.hasPointerCapture(e.pointerId))this.canvas.releasePointerCapture(e.pointerId);this.active=null};
private redraw(){const r=this.canvas.getBoundingClientRect();this.ctx.clearRect(0,0,r.width,r.height);this.ctx.lineCap='round';this.ctx.lineJoin='round';for(const s of this.strokes){this.ctx.save();this.ctx.globalCompositeOperation=s.eraser?'destination-out':'source-over';this.ctx.strokeStyle='#1d1d1f';for(let i=1;i<s.points.length;i++){const a=s.points[i-1],b=s.points[i];if(!a||!b)continue;this.ctx.beginPath();this.ctx.lineWidth=s.eraser?24:2.5+b.pressure*2.5;this.ctx.moveTo(a.x,a.y);this.ctx.lineTo(b.x,b.y);this.ctx.stroke()}this.ctx.restore()}}
}
