import type { StudyCard, SyncQueueItem } from '../types.js';
import { initialSchedule } from '../scheduler/scheduler.js';
import { DEFAULT_DECK_ID, DEFAULT_PROFILE_ID, BASIC_NOTE_TYPE_ID } from '../anki/defaults.js';
import { nowIso, normalizeTags, uid } from '../utils/core.js';
import { saveCard, saveQueueItem } from '../storage/db.js';
export interface CardDraft{cardNumber?:string;question:string;answer:string;distractors:string[];explanation:string;tagsText:string;favorite:boolean}
export function createCard(draft:CardDraft,now=new Date()):StudyCard{const t=now.toISOString();const id=uid('card');return{id,cardNumber:draft.cardNumber?.trim()??'',question:draft.question.trim(),answer:draft.answer.trim(),distractors:draft.distractors.map(v=>v.trim()).filter(Boolean).slice(0,3),explanation:draft.explanation.trim(),tags:normalizeTags(draft.tagsText),favorite:draft.favorite,createdAt:t,updatedAt:t,deletedAt:null,schedule:initialSchedule(now),stats:{correct:0,incorrect:0,totalTimeMs:0,fastestMs:null,lastTimesMs:[]},version:1,profileId:DEFAULT_PROFILE_ID,deckId:DEFAULT_DECK_ID,noteId:`legacy_note_${id}`,noteTypeId:BASIC_NOTE_TYPE_ID,templateId:'template_basic_forward',queue:'new',position:now.getTime(),flag:0,suspended:false,buriedUntil:null,marked:draft.favorite,siblingGroup:`legacy_note_${id}`,filteredDeckId:null,customData:{}}}
export function validateCardDraft(draft:CardDraft):string[]{const e:string[]=[];if(!draft.question.trim())e.push('問題文を入力してください。');if(!draft.answer.trim())e.push('正解を入力してください。');if((draft.cardNumber?.length??0)>100)e.push('カード番号は100文字以内にしてください。');if(draft.question.length>5000)e.push('問題文は5000文字以内にしてください。');if(draft.answer.length>5000)e.push('正解は5000文字以内にしてください。');if(draft.explanation.length>10000)e.push('解説は10000文字以内にしてください。');return e}
export async function persistCard(card:StudyCard,action:'upsertCard'|'deleteCard'='upsertCard'):Promise<void>{const requestId=uid('req');const next={...card,lastRequestId:requestId};await saveCard(next);const item:SyncQueueItem={requestId,action,payload:{card:next},createdAt:nowIso(),attempts:0};await saveQueueItem(item)}
